name: Node.js CI for the front-end 🚀
run-name: ${{ github.actor }} is testing and deploying front-end 🚀
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]
    
    defaults:
      run:
        working-directory: front-end

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: front-end/package-lock.json
    - run: npm ci
    - run: npm test
    - run: npm run build --if-present
    - name: Commit and push build output
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add -A
        if git diff-index --quiet HEAD; then
          echo "No changes to commit"
        else
          git commit -m "Build front-end"
          git push
        fi
        
